# Application Name
spring.application.name=activityservice

# MongoDB Configuration (IMPORTANT)
spring.data.mongodb.uri=mongodb://localhost:27017/activity_service_db
spring.data.mongodb.database=activity_service_db

# Server Port
server.port=8082